//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderOnlineAPI.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_info()
        {
            this.order_item = new HashSet<order_item>();
        }
    
        public int OrderinfoId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public System.DateTime CreatTime { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_item> order_item { get; set; }
        public virtual user_info user_info { get; set; }
    }
}
