//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderOnlineAPI.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class production_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public production_info()
        {
            this.production_picture = new HashSet<production_picture>();
        }
    
        public int ProductionId { get; set; }
        public string ProdName { get; set; }
        public decimal ProdPrice { get; set; }
        public string ProdRemarks { get; set; }
        public string ProdmainPictures { get; set; }
        public Nullable<int> ProdsaleCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<production_picture> production_picture { get; set; }
    }
}
